server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: ${POSTGRES_URL} #jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER} #root
    password: ${POSTGRES_PASSWORD} #password
  jpa:
    hibernate:
      ddl-auto: ${POSTGRES_DDLAUTO} #create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  rabbitmq:
    addressUrl: ${RABBITMQ_ADDRESSURL} #'http://localhost:15672'
    queue: ${RABBITMQ_QUEUE} #email